module.exports = function () {
  return {
    'free-regular-svg-icons': [
      'check-square',
      'circle',
      'dot-circle',
      'square',
      'circle-xmark',
    ],
    'free-solid-svg-icons': [
      'angle-up',
      'bookmark',
      'caret-down',
      'caret-up',
      'check-square',
      'chevron-down',
      'chevron-left',
      'chevron-up',
      'circle',
      'exclamation-triangle',
      'external-link-alt',
      'home',
      'info-circle',
      'link',
      'map-pin',
      'minus',
      'pen',
      'plus',
      'print',
      'search',
      'spinner',
      'square',
      'times',
      'tree',
      'undo',
      'window-minimize',
      'dollar-sign',
      'street-view',
      'bolt',
      'equals',
      'users-between-lines',
      'road',
      'people-roof',
    ],
  };
};
